DEF TILE_WIDTH EQU 8 ; pixels

DEF NUM_PAL_COLORS EQU 4
DEF PAL_COLOR_SIZE EQU 2
DEF PALETTE_SIZE EQU NUM_PAL_COLORS * PAL_COLOR_SIZE

DEF PALRGB_WHITE EQUS "palred 31 + palgreen 31 + palblue 31" ; $7fff

; tile size
DEF TILE_SIZE EQU 16 ; bytes
DEF tiles EQUS "* TILE_SIZE"
DEF tile  EQUS "+ TILE_SIZE *"

; fading speed used by wFadeSpeed
	const_def
	const FADE_SPEED_SLOW   ; $00
	const FADE_SPEED_NORMAL ; $01
	const FADE_SPEED_FAST   ; $02

DEF SCREEN_WIDTH  EQU 20 ; tiles
DEF SCREEN_HEIGHT EQU 18 ; tiles
DEF SCREEN_WIDTH_PX  EQU SCREEN_WIDTH  * TILE_WIDTH ; pixels
DEF SCREEN_HEIGHT_PX EQU SCREEN_HEIGHT * TILE_WIDTH ; pixels

DEF BG_MAP_WIDTH  EQU 32 ; tiles
DEF BG_MAP_HEIGHT EQU 32 ; tiles

DEF METATILE_WIDTH EQU 4 ; tiles
DEF SCREEN_META_WIDTH EQU 6 ; metatiles
DEF SCREEN_META_HEIGHT EQU 5 ; metatiles
DEF SURROUNDING_WIDTH  EQU SCREEN_META_WIDTH * METATILE_WIDTH ; tiles
DEF SURROUNDING_HEIGHT EQU SCREEN_META_HEIGHT * METATILE_WIDTH ; tiles

; sprite_oam_struct members (see macros/wram.asm)
	const_def
	const SPRITEOAMSTRUCT_YCOORD     ; 0
	const SPRITEOAMSTRUCT_XCOORD     ; 1
	const SPRITEOAMSTRUCT_TILE_ID    ; 2
	const SPRITEOAMSTRUCT_ATTRIBUTES ; 3
DEF SPRITEOAMSTRUCT_LENGTH EQU const_value
DEF NUM_SPRITE_OAM_STRUCTS EQU 40 ; see wVirtualOAM

DEF SPRITE_GFX_LIST_CAPACITY EQU 32 ; see wUsedSprites

; colour_part_fade_struct members (see macros/wram.asm)
	const_def
	const COLOURFADESTRUCT_BASE        ; 0
	const COLOURFADESTRUCT_TARGET      ; 1
	const COLOURFADESTRUCT_SIGN        ; 2
	const COLOURFADESTRUCT_DIFF        ; 3
	const COLOURFADESTRUCT_ACCUMULATOR ; 4
	const COLOURFADESTRUCT_CURRENT     ; 5
	const COLOURFADESTRUCT_UNK_3       ; 6
	const COLOURFADESTRUCT_UNK_4       ; 7
DEF COLOURFADESTRUCT_LENGTH EQU const_value
