; flags for wGameModeFlags
	const_def
	const MODE_GAME_CLEARED_F           ; 0
	const MODE_TIME_ATTACK_F            ; 1
	const MODE_FOUGHT_A_HIDDEN_FIGURE_F ; 2

MODE_GAME_CLEARED           EQU 1 << MODE_GAME_CLEARED_F
MODE_TIME_ATTACK            EQU 1 << MODE_TIME_ATTACK_F
MODE_FOUGHT_A_HIDDEN_FIGURE EQU 1 << MODE_FOUGHT_A_HIDDEN_FIGURE_F

; special wTransitionParam values
DEF TRANSITION_RETURN_TO_MAP        EQU $f0
DEF TRANSITION_EPILOGUE_NOT_PERFECT EQU $f1
DEF TRANSITION_EPILOGUE_PERFECT     EQU $f2
DEF TRANSITION_GAME_OVER            EQU $f3
DEF TRANSITION_NEW_GAME             EQU $ff

; wTimeAttackResult constants
	const_def
	const TIME_ATTACK_NOT_COMPLETED  ; $0
	const TIME_ATTACK_NO_HIGH_SCORE  ; $1
	const TIME_ATTACK_GOT_HIGH_SCORE ; $2
