; Boolean checks
DEF FALSE EQU 0
DEF TRUE  EQU 1

DEF NULL EQU $ffff

DEF LCDC_DEFAULT EQU LCDC_BG_ON | LCDC_OBJ_ON | LCDC_OBJ_16 | LCDC_ON

; save corruption constants
DEF CHECKVAL1_1 EQU $77
DEF CHECKVAL1_2 EQU $61
DEF CHECKVAL1_3 EQU $72
DEF CHECKVAL1_4 EQU $33

DEF CHECKVAL2_1 EQU $57
DEF CHECKVAL2_2 EQU $41
DEF CHECKVAL2_3 EQU $52
DEF CHECKVAL2_4 EQU $33

    const_def
    const MISMATCH_ORIG_F  ; $0
    const MISMATCH_ECHO1_F ; $1
    const MISMATCH_ECHO2_F ; $2

DEF MISMATCH_ORIG  EQU 1 << MISMATCH_ORIG_F
DEF MISMATCH_ECHO1 EQU 1 << MISMATCH_ECHO1_F
DEF MISMATCH_ECHO2 EQU 1 << MISMATCH_ECHO2_F
