DIRECTION_LEFT  EQU 0
DIRECTION_RIGHT EQU 1

; jump vel constants
MAX_JUMP_VEL_INDEX     EQU $27
FALLING_JUMP_VEL_INDEX EQU $18

	const_def
	const JUMP_VEL_NONE             ; 0
	const JUMP_VEL_KNOCK_BACK       ; 1
	const JUMP_VEL_NORMAL           ; 2
	const JUMP_VEL_HIGH_JUMP        ; 3
	const JUMP_VEL_BOUNCY_JUMP      ; 4
	const JUMP_VEL_BOUNCY_HIGH_JUMP ; 5

; number of times Wario has to wiggle
; to escape being picked up in the duration window
NUM_WIGGLES_TO_ESCAPE EQU 6
; duration window that Wario can decrement
MAX_PICKED_UP_FRAME_COUNTER EQU 32

; wFloorTransitionDir flags
FLOOR_TRANSITION_DOWN_F EQU 2
FLOOR_TRANSITION_UP_F   EQU 3

FLOOR_TRANSITION_DOWN  EQU 1 << FLOOR_TRANSITION_DOWN_F
FLOOR_TRANSITION_UP    EQU 1 << FLOOR_TRANSITION_UP_F

; wCameraConfigFlags constants
	const_def
	const CAMCONFIG_FREE_F        ; 0
	const CAMCONFIG_XSCROLL1_F    ; 1
	const CAMCONFIG_XSCROLL2_F    ; 2
	const CAMCONFIG_TRANSITIONS_F ; 3

	const CAMCONFIG_EDGE_RIGHT_F  ; 4
	const CAMCONFIG_EDGE_LEFT_F   ; 5
	const CAMCONFIG_EDGE_UP_F     ; 6
	const CAMCONFIG_EDGE_DOWN_F   ; 7

CAMCONFIG_YSCROLL     EQU 0
CAMCONFIG_FREE        EQU 1 << CAMCONFIG_FREE_F
CAMCONFIG_XSCROLL1    EQU 1 << CAMCONFIG_XSCROLL1_F
CAMCONFIG_XSCROLL2    EQU 1 << CAMCONFIG_XSCROLL2_F
CAMCONFIG_TRANSITIONS EQU 1 << CAMCONFIG_TRANSITIONS_F

CAMCONFIG_SCROLLING_MASK EQU $0f

CAMCONFIG_EDGE_RIGHT EQU 1 << CAMCONFIG_EDGE_RIGHT_F
CAMCONFIG_EDGE_LEFT  EQU 1 << CAMCONFIG_EDGE_LEFT_F

HIDDEN_FIGURE_CAMCONFIG EQU CAMCONFIG_XSCROLL2 | CAMCONFIG_TRANSITIONS | CAMCONFIG_EDGE_RIGHT | CAMCONFIG_EDGE_LEFT

; flags set for wWaterCurrent
	const_def
	const WATER_CURRENT_RIGHT_F ; 0
	const WATER_CURRENT_LEFT_F  ; 1
	const WATER_CURRENT_UP_F    ; 2
	const WATER_CURRENT_DOWN_F  ; 3

WATER_CURRENT_RIGHT EQU 1 << WATER_CURRENT_RIGHT_F
WATER_CURRENT_LEFT  EQU 1 << WATER_CURRENT_LEFT_F
WATER_CURRENT_UP    EQU 1 << WATER_CURRENT_UP_F
WATER_CURRENT_DOWN  EQU 1 << WATER_CURRENT_DOWN_F
