	const_def
	const MAP_NORTH ; $0
	const MAP_WEST  ; $1
	const MAP_SOUTH ; $2
	const MAP_EAST  ; $3

	const_def
	const CRAYON_RED_F    ; 0
	const CRAYON_BROWN_F  ; 1
	const CRAYON_YELLOW_F ; 2
	const CRAYON_GREEN_F  ; 3
	const CRAYON_CYAN_F   ; 4
	const CRAYON_BLUE_F   ; 5
	const CRAYON_PINK_F   ; 6

CRAYON_RED    EQU 1 << CRAYON_RED_F    ; $01
CRAYON_BROWN  EQU 1 << CRAYON_BROWN_F  ; $02
CRAYON_YELLOW EQU 1 << CRAYON_YELLOW_F ; $04
CRAYON_GREEN  EQU 1 << CRAYON_GREEN_F  ; $08
CRAYON_CYAN   EQU 1 << CRAYON_CYAN_F   ; $10
CRAYON_BLUE   EQU 1 << CRAYON_BLUE_F   ; $20
CRAYON_PINK   EQU 1 << CRAYON_PINK_F   ; $40

ALL_CRAYONS EQU CRAYON_RED | CRAYON_BROWN | CRAYON_YELLOW | CRAYON_GREEN | CRAYON_CYAN | CRAYON_BLUE | CRAYON_PINK