	const_def

	const SOUND_OFF                        ; 000

	const MUSIC_OUT_OF_THE_WOODS_DAY       ; 001
	const MUSIC_OUT_OF_THE_WOODS_NIGHT     ; 002
	const MUSIC_FOREST_OF_FEAR             ; 003
	const MUSIC_THE_WARPED_VOID            ; 004
	const MUSIC_DESERT_RUINS               ; 005
	const MUSIC_THE_FRIGID_SEA             ; 006
	const MUSIC_THE_PEACEFUL_VILLAGE_DAY   ; 007
	const MUSIC_THE_PEACEFUL_VILLAGE_NIGHT ; 008
	const MUSIC_ABOVE_THE_CLOUDS_DAY       ; 009
	const MUSIC_ABOVE_THE_CLOUDS_NIGHT     ; 00a
	const MUSIC_THE_VOLCANOS_BASE_NIGHT    ; 00b
	const MUSIC_THE_VOLCANOS_BASE_DAY      ; 00c
	const MUSIC_THE_WEST_CRATER            ; 00d
	const MUSIC_THE_VAST_PLAIN_DAY         ; 00e
	const MUSIC_THE_VAST_PLAIN_NIGHT       ; 00f
	const MUSIC_BANK_OF_THE_WILD_RIVER     ; 010
	const MUSIC_THE_TIDAL_COAST            ; 011
	const MUSIC_CAVE_OF_FLAMES             ; 012
	const MUSIC_THE_POOL_OF_RAIN_DAY       ; 013
	const MUSIC_THE_POOL_OF_RAIN_NIGHT     ; 014
	const MUSIC_CREDITS                    ; 015
	const MUSIC_HOT_WARIO                  ; 016
	const MUSIC_FAT_WARIO                  ; 017
	const MUSIC_BOUNCY_WARIO               ; 018
	const MUSIC_ZOMBIE_WARIO               ; 019
	const MUSIC_FLAT_WARIO                 ; 01a
	const MUSIC_CRAZY_WARIO                ; 01b
	const MUSIC_INVISIBLE_WARIO            ; 01c
	const MUSIC_SNOWMAN_WARIO              ; 01d
	const MUSIC_OWL_WARIO                  ; 01e
	const MUSIC_BALL_O_STRING_WARIO        ; 01f
	const MUSIC_VAMPIRE_WARIO              ; 020
	const MUSIC_OVERWORLD_DAY              ; 021
	const MUSIC_OVERWORLD_NIGHT            ; 022
	const MUSIC_LEVEL_CLEAR_NO_TREASURE    ; 023
	const MUSIC_TREASURE_FANFARE           ; 024
	const MUSIC_PAUSE_MENU                 ; 025
	const MUSIC_GOLF                       ; 026
	const MUSIC_BOSS_BATTLE                ; 027
	const MUSIC_LEVEL_CLEAR_GOT_TREASURE   ; 028
	const MUSIC_BOSS_DEFEAT                ; 029
	const MUSIC_GOLF_NOT_CLEARED           ; 02a
	const MUSIC_GOLF_CLEARED               ; 02b
	const MUSIC_MUSIC_BOXES                ; 02c
	const MUSIC_45                         ; 02d
	const MUSIC_POWER_UP_DEMO              ; 02e
	const MUSIC_GOLF_ROOM                  ; 02f
	const MUSIC_48                         ; 030
	const MUSIC_49                         ; 031
	const MUSIC_THE_TEMPLE                 ; 032
	const MUSIC_TITLE_SCREEN               ; 033
	const MUSIC_INTRO                      ; 034
	const MUSIC_HIDDEN_FIGURE_BATTLE_1     ; 035
	const MUSIC_PERFECT                    ; 036
	const MUSIC_TREASURE_COLLECTION        ; 037
	const MUSIC_OUTRO                      ; 038
	const MUSIC_HIDDEN_FIGURE_REVEAL       ; 039
	const MUSIC_HIDDEN_FIGURE_BATTLE_2     ; 03a
