	const_def

	const SOUND_OFF                        ; 000

	const MUSIC_OUT_OF_THE_WOODS_DAY       ; 001
	const MUSIC_OUT_OF_THE_WOODS_NIGHT     ; 002
	const MUSIC_FOREST_OF_FEAR             ; 003
	const MUSIC_THE_WARPED_VOID            ; 004
	const MUSIC_DESERT_RUINS               ; 005
	const MUSIC_THE_FRIGID_SEA             ; 006
	const MUSIC_THE_PEACEFUL_VILLAGE_DAY   ; 007
	const MUSIC_THE_PEACEFUL_VILLAGE_NIGHT ; 008
	const MUSIC_ABOVE_THE_CLOUDS_DAY       ; 009
	const MUSIC_ABOVE_THE_CLOUDS_NIGHT     ; 00a
	const MUSIC_THE_VOLCANOS_BASE_NIGHT    ; 00b
	const MUSIC_THE_VOLCANOS_BASE_DAY      ; 00c
	const MUSIC_THE_WEST_CRATER            ; 00d
	const MUSIC_THE_VAST_PLAIN_DAY         ; 00e
	const MUSIC_THE_VAST_PLAIN_NIGHT       ; 00f
	const MUSIC_BANK_OF_THE_WILD_RIVER     ; 010
	const MUSIC_THE_TIDAL_COAST            ; 011
	const MUSIC_CAVE_OF_FLAMES             ; 012
	const MUSIC_THE_POOL_OF_RAIN_DAY       ; 013
	const MUSIC_THE_POOL_OF_RAIN_NIGHT     ; 014
	const MUSIC_CREDITS                    ; 015
	const MUSIC_HOT_WARIO                  ; 016
	const MUSIC_FAT_WARIO                  ; 017
	const MUSIC_BOUNCY_WARIO               ; 018
	const MUSIC_ZOMBIE_WARIO               ; 019
	const MUSIC_FLAT_WARIO                 ; 01a
	const MUSIC_CRAZY_WARIO                ; 01b
	const MUSIC_INVISIBLE_WARIO            ; 01c
	const MUSIC_SNOWMAN_WARIO              ; 01d
	const MUSIC_OWL_WARIO                  ; 01e
	const MUSIC_BALL_O_STRING_WARIO        ; 01f
	const MUSIC_VAMPIRE_WARIO              ; 020
	const MUSIC_OVERWORLD_DAY              ; 021
	const MUSIC_OVERWORLD_NIGHT            ; 022
	const MUSIC_LEVEL_CLEAR_NO_TREASURE    ; 023
	const MUSIC_TREASURE_FANFARE           ; 024
	const MUSIC_PAUSE_MENU                 ; 025
	const MUSIC_GOLF                       ; 026
	const MUSIC_BOSS_BATTLE                ; 027
	const MUSIC_LEVEL_CLEAR_GOT_TREASURE   ; 028
	const MUSIC_BOSS_DEFEAT                ; 029
	const MUSIC_GOLF_NOT_CLEARED           ; 02a
	const MUSIC_GOLF_CLEARED               ; 02b
	const MUSIC_MUSIC_BOXES                ; 02c
	const MUSIC_45                         ; 02d
	const MUSIC_POWER_UP_DEMO              ; 02e
	const MUSIC_GOLF_ROOM                  ; 02f
	const MUSIC_48                         ; 030
	const MUSIC_49                         ; 031
	const MUSIC_THE_TEMPLE                 ; 032
	const MUSIC_TITLE_SCREEN               ; 033
	const MUSIC_INTRO                      ; 034
	const MUSIC_HIDDEN_FIGURE_BATTLE_1     ; 035
	const MUSIC_PERFECT                    ; 036
	const MUSIC_TREASURE_COLLECTION        ; 037
	const MUSIC_OUTRO                      ; 038
	const MUSIC_HIDDEN_FIGURE_REVEAL       ; 039
	const MUSIC_HIDDEN_FIGURE_BATTLE_2     ; 03a

	const_def $101
	const SFX_01                           ; 101
	const SFX_02                           ; 102
	const SFX_03                           ; 103
	const SFX_04                           ; 104
	const SFX_05                           ; 105
	const SFX_06                           ; 106
	const SFX_07                           ; 107
	const SFX_08                           ; 108
	const SFX_09                           ; 109
	const SFX_0A                           ; 10a
	const SFX_0B                           ; 10b
	const SFX_0C                           ; 10c
	const SFX_0D                           ; 10d
	const SFX_0E                           ; 10e
	const SFX_0F                           ; 10f
	const SFX_10                           ; 110
	const SFX_11                           ; 111
	const SFX_12                           ; 112
	const SFX_13                           ; 113
	const SFX_14                           ; 114
	const SFX_15                           ; 115
	const SFX_16                           ; 116
	const SFX_17                           ; 117
	const SFX_18                           ; 118
	const SFX_19                           ; 119
	const SFX_1A                           ; 11a
	const SFX_1B                           ; 11b
	const SFX_1C                           ; 11c
	const SFX_1D                           ; 11d
	const SFX_1E                           ; 11e
	const SFX_1F                           ; 11f
	const SFX_20                           ; 120
	const SFX_21                           ; 121
	const SFX_22                           ; 122
	const SFX_23                           ; 123
	const SFX_24                           ; 124
	const SFX_25                           ; 125
	const SFX_26                           ; 126
	const SFX_27                           ; 127
	const SFX_28                           ; 128
	const SFX_29                           ; 129
	const SFX_2A                           ; 12a
	const SFX_2B                           ; 12b
	const SFX_2C                           ; 12c
	const SFX_2D                           ; 12d
	const SFX_2E                           ; 12e
	const SFX_2F                           ; 12f
	const SFX_30                           ; 130
	const SFX_31                           ; 131
	const SFX_32                           ; 132
	const SFX_33                           ; 133
	const SFX_34                           ; 134
	const SFX_35                           ; 135
	const SFX_36                           ; 136
	const SFX_37                           ; 137
	const SFX_38                           ; 138
	const SFX_39                           ; 139
	const SFX_3A                           ; 13a
	const SFX_3B                           ; 13b
	const SFX_3C                           ; 13c
	const SFX_3D                           ; 13d
	const SFX_3E                           ; 13e
	const SFX_3F                           ; 13f
	const SFX_40                           ; 140
	const SFX_41                           ; 141
	const SFX_42                           ; 142
	const SFX_43                           ; 143
	const SFX_44                           ; 144
	const SFX_45                           ; 145
	const SFX_46                           ; 146
	const SFX_47                           ; 147
	const SFX_48                           ; 148
	const SFX_49                           ; 149
	const SFX_4A                           ; 14a
	const SFX_4B                           ; 14b
	const SFX_4C                           ; 14c
	const SFX_4D                           ; 14d
	const SFX_4E                           ; 14e
	const SFX_4F                           ; 14f
	const SFX_50                           ; 150
	const SFX_51                           ; 151
	const SFX_52                           ; 152
	const SFX_53                           ; 153
	const SFX_54                           ; 154
	const SFX_55                           ; 155
	const SFX_56                           ; 156
	const SFX_57                           ; 157
	const SFX_58                           ; 158
	const SFX_59                           ; 159
	const SFX_5A                           ; 15a
	const SFX_5B                           ; 15b
	const SFX_5C                           ; 15c
	const SFX_5D                           ; 15d
	const SFX_5E                           ; 15e
	const SFX_5F                           ; 15f
	const SFX_60                           ; 160
	const SFX_61                           ; 161
	const SFX_62                           ; 162
	const SFX_63                           ; 163
	const SFX_64                           ; 164
	const SFX_65                           ; 165
	const SFX_66                           ; 166
	const SFX_67                           ; 167
	const SFX_68                           ; 168
	const SFX_69                           ; 169
	const SFX_6A                           ; 16a
	const SFX_6B                           ; 16b
	const SFX_6C                           ; 16c
	const SFX_6D                           ; 16d
	const SFX_6E                           ; 16e
	const SFX_6F                           ; 16f
	const SFX_70                           ; 170
	const SFX_71                           ; 171
	const SFX_72                           ; 172
	const SFX_73                           ; 173
	const SFX_74                           ; 174
	const SFX_75                           ; 175
	const SFX_76                           ; 176
	const SFX_77                           ; 177
	const SFX_78                           ; 178
	const SFX_79                           ; 179
	const SFX_7A                           ; 17a
	const SFX_7B                           ; 17b
	const SFX_7C                           ; 17c
	const SFX_7D                           ; 17d
	const SFX_7E                           ; 17e
	const SFX_7F                           ; 17f
	const SFX_80                           ; 180
	const SFX_81                           ; 181
	const SFX_82                           ; 182
	const SFX_83                           ; 183
	const SFX_84                           ; 184
	const SFX_85                           ; 185
	const SFX_86                           ; 186
	const SFX_87                           ; 187
	const SFX_88                           ; 188
	const SFX_89                           ; 189
	const SFX_8A                           ; 18a
	const SFX_8B                           ; 18b
	const SFX_8C                           ; 18c
	const SFX_8D                           ; 18d
	const SFX_8E                           ; 18e
	const SFX_8F                           ; 18f
	const SFX_90                           ; 190
	const SFX_91                           ; 191
	const SFX_92                           ; 192
	const SFX_93                           ; 193
	const SFX_94                           ; 194
	const SFX_95                           ; 195
	const SFX_96                           ; 196
	const SFX_97                           ; 197
	const SFX_98                           ; 198
	const SFX_99                           ; 199
	const SFX_9A                           ; 19a
	const SFX_9B                           ; 19b
	const SFX_9C                           ; 19c
	const SFX_9D                           ; 19d
	const SFX_9E                           ; 19e
	const SFX_9F                           ; 19f
	const SFX_A0                           ; 1a0
	const SFX_A1                           ; 1a1
	const SFX_A2                           ; 1a2
	const SFX_A3                           ; 1a3
	const SFX_A4                           ; 1a4
	const SFX_A5                           ; 1a5
	const SFX_A6                           ; 1a6
	const SFX_A7                           ; 1a7
	const SFX_A8                           ; 1a8
	const SFX_A9                           ; 1a9
	const SFX_AA                           ; 1aa
	const SFX_AB                           ; 1ab
	const SFX_AC                           ; 1ac
	const SFX_AD                           ; 1ad
	const SFX_AE                           ; 1ae
	const SFX_AF                           ; 1af
	const SFX_B0                           ; 1b0
	const SFX_B1                           ; 1b1
	const SFX_B2                           ; 1b2
	const SFX_B3                           ; 1b3
	const SFX_B4                           ; 1b4
	const SFX_B5                           ; 1b5
	const SFX_B6                           ; 1b6
	const SFX_B7                           ; 1b7
	const SFX_B8                           ; 1b8
	const SFX_B9                           ; 1b9
	const SFX_BA                           ; 1ba
	const SFX_BB                           ; 1bb
	const SFX_BC                           ; 1bc
	const SFX_BD                           ; 1bd
	const SFX_BE                           ; 1be
	const SFX_BF                           ; 1bf
	const SFX_C0                           ; 1c0
	const SFX_C1                           ; 1c1
	const SFX_C2                           ; 1c2
	const SFX_C3                           ; 1c3
	const SFX_C4                           ; 1c4
	const SFX_C5                           ; 1c5
	const SFX_C6                           ; 1c6
	const SFX_C7                           ; 1c7
	const SFX_C8                           ; 1c8
	const SFX_C9                           ; 1c9
	const SFX_CA                           ; 1ca
	const SFX_CB                           ; 1cb
	const SFX_CC                           ; 1cc
	const SFX_CD                           ; 1cd
	const SFX_CE                           ; 1ce
	const SFX_CF                           ; 1cf
	const SFX_D0                           ; 1d0
	const SFX_D1                           ; 1d1
	const SFX_D2                           ; 1d2
	const SFX_D3                           ; 1d3
	const SFX_D4                           ; 1d4
	const SFX_D5                           ; 1d5
	const SFX_D6                           ; 1d6
	const SFX_D7                           ; 1d7
	const SFX_D8                           ; 1d8
	const SFX_D9                           ; 1d9
	const SFX_DA                           ; 1da
	const SFX_DB                           ; 1db
	const SFX_DC                           ; 1dc
	const SFX_DD                           ; 1dd
	const SFX_DE                           ; 1de
	const SFX_DF                           ; 1df
	const SFX_E0                           ; 1e0
	const SFX_E1                           ; 1e1
	const SFX_E2                           ; 1e2
	const SFX_E3                           ; 1e3
	const SFX_E4                           ; 1e4
	const SFX_E5                           ; 1e5
	const SFX_E6                           ; 1e6
	const SFX_E7                           ; 1e7
	const SFX_E8                           ; 1e8
	const SFX_E9                           ; 1e9
	const SFX_EA                           ; 1ea
	const SFX_EB                           ; 1eb
	const SFX_EC                           ; 1ec
	const SFX_ED                           ; 1ed
	const SFX_EE                           ; 1ee
	const SFX_EF                           ; 1ef
