	const_def

	const SOUND_OFF                        ; 000

	const MUSIC_OUT_OF_THE_WOODS_DAY       ; 001
	const MUSIC_OUT_OF_THE_WOODS_NIGHT     ; 002
	const MUSIC_FOREST_OF_FEAR             ; 003
	const MUSIC_THE_WARPED_VOID            ; 004
	const MUSIC_DESERT_RUINS               ; 005
	const MUSIC_THE_FRIGID_SEA             ; 006
	const MUSIC_THE_PEACEFUL_VILLAGE_DAY   ; 007
	const MUSIC_THE_PEACEFUL_VILLAGE_NIGHT ; 008
	const MUSIC_ABOVE_THE_CLOUDS_DAY       ; 009
	const MUSIC_ABOVE_THE_CLOUDS_NIGHT     ; 00a
	const MUSIC_THE_VOLCANOS_BASE_NIGHT    ; 00b
	const MUSIC_THE_VOLCANOS_BASE_DAY      ; 00c
	const MUSIC_THE_WEST_CRATER            ; 00d
	const MUSIC_THE_VAST_PLAIN_DAY         ; 00e
	const MUSIC_THE_VAST_PLAIN_NIGHT       ; 00f
	const MUSIC_BANK_OF_THE_WILD_RIVER     ; 010
	const MUSIC_THE_TIDAL_COAST            ; 011
	const MUSIC_CAVE_OF_FLAMES             ; 012
	const MUSIC_THE_POOL_OF_RAIN_DAY       ; 013
	const MUSIC_THE_POOL_OF_RAIN_NIGHT     ; 014
	const MUSIC_CREDITS                    ; 015
	const MUSIC_HOT_WARIO                  ; 016
	const MUSIC_FAT_WARIO                  ; 017
	const MUSIC_BOUNCY_WARIO               ; 018
	const MUSIC_ZOMBIE_WARIO               ; 019
	const MUSIC_FLAT_WARIO                 ; 01a
	const MUSIC_CRAZY_WARIO                ; 01b
	const MUSIC_INVISIBLE_WARIO            ; 01c
	const MUSIC_SNOWMAN_WARIO              ; 01d
	const MUSIC_OWL_WARIO                  ; 01e
	const MUSIC_BALL_O_STRING_WARIO        ; 01f
	const MUSIC_VAMPIRE_WARIO              ; 020
	const MUSIC_OVERWORLD_DAY              ; 021
	const MUSIC_OVERWORLD_NIGHT            ; 022
	const MUSIC_LEVEL_CLEAR_NO_TREASURE    ; 023
	const MUSIC_TREASURE_FANFARE           ; 024
	const MUSIC_PAUSE_MENU                 ; 025
	const MUSIC_GOLF                       ; 026
	const MUSIC_BOSS_BATTLE                ; 027
	const MUSIC_LEVEL_CLEAR_GOT_TREASURE   ; 028
	const MUSIC_BOSS_DEFEAT                ; 029
	const MUSIC_GOLF_NOT_CLEARED           ; 02a
	const MUSIC_GOLF_CLEARED               ; 02b
	const MUSIC_MUSIC_BOXES                ; 02c
	const MUSIC_45                         ; 02d
	const MUSIC_POWER_UP_DEMO              ; 02e
	const MUSIC_GOLF_ROOM                  ; 02f
	const MUSIC_48                         ; 030
	const MUSIC_49                         ; 031
	const MUSIC_THE_TEMPLE                 ; 032
	const MUSIC_TITLE_SCREEN               ; 033
	const MUSIC_INTRO                      ; 034
	const MUSIC_HIDDEN_FIGURE_BATTLE_1     ; 035
	const MUSIC_PERFECT                    ; 036
	const MUSIC_TREASURE_COLLECTION        ; 037
	const MUSIC_OUTRO                      ; 038
	const MUSIC_HIDDEN_FIGURE_REVEAL       ; 039
	const MUSIC_HIDDEN_FIGURE_BATTLE_2     ; 03a

	const_def $101
	const SFX_01                           ; 101
	const SFX_02                           ; 102
	const SFX_03                           ; 103
	const SFX_04                           ; 104
	const SFX_05                           ; 105
	const SFX_06                           ; 106
	const SFX_07                           ; 107
	const SFX_08                           ; 108
	const SFX_09                           ; 109
	const SFX_0a                           ; 10a
	const SFX_0b                           ; 10b
	const SFX_0c                           ; 10c
	const SFX_0d                           ; 10d
	const SFX_0e                           ; 10e
	const SFX_0f                           ; 10f
	const SFX_10                           ; 110
	const SFX_11                           ; 111
	const SFX_12                           ; 112
	const SFX_13                           ; 113
	const SFX_14                           ; 114
	const SFX_15                           ; 115
	const SFX_16                           ; 116
	const SFX_17                           ; 117
	const SFX_18                           ; 118
	const SFX_19                           ; 119
	const SFX_1a                           ; 11a
	const SFX_1b                           ; 11b
	const SFX_1c                           ; 11c
	const SFX_1d                           ; 11d
	const SFX_1e                           ; 11e
	const SFX_1f                           ; 11f
	const SFX_21                           ; 121
	const SFX_22                           ; 122
	const SFX_23                           ; 123
	const SFX_24                           ; 124
	const SFX_25                           ; 125
	const SFX_26                           ; 126
	const SFX_27                           ; 127
	const SFX_28                           ; 128
	const SFX_29                           ; 129
	const SFX_2a                           ; 12a
	const SFX_2b                           ; 12b
	const SFX_2c                           ; 12c
	const SFX_2d                           ; 12d
	const SFX_2e                           ; 12e
	const SFX_2f                           ; 12f
