	const_def                
	const ST_IDLING                        ; 00
	const ST_WALKING                       ; 01
	const ST_TURNING                       ; 02
	const ST_UNKNOWN_03                    ; 03
	const ST_AIRBORNE                      ; 04
	const ST_LANDING                       ; 05
	const ST_CROUCH_SLIDING                ; 06
	const ST_ATTACKING                     ; 07
	const ST_ATTACKING_AIRBORNE            ; 08
	const ST_ATTACK_KNOCK_BACK             ; 09
	const ST_DIVING                        ; 0a
	const ST_SUBMERGED                     ; 0b
	const ST_WATER_SURFACE_IDLING          ; 0c
	const ST_WATER_SURFACE_MOVING          ; 0d
	const ST_UNDERWATER_THRUSTING          ; 0e
	const ST_SWIM_KNOCK_BACK               ; 0f
	const ST_WATER_STUNG                   ; 10
	const ST_TRYING_SUBMERGE               ; 11
	const ST_CROUCHING                     ; 12
	const ST_CROUCH_WALKING                ; 13
	const ST_CROUCH_AIRBORNE               ; 14
	const ST_STUNG                         ; 15
	const ST_STUNG_RECOVERY                ; 16
	const ST_PIPE_GOING_DOWN               ; 17
	const ST_PIPE_GOING_UP                 ; 18
	const ST_UNKNOWN_19                    ; 19
	const ST_SMASH_ATTACKING               ; 1a
	const ST_UNKNOWN_1B                    ; 1b
	const ST_UNKNOWN_1C                    ; 1c
	const ST_UNKNOWN_1D                    ; 1d
	const ST_PICKING_UP                    ; 1e
	const ST_GRAB_IDLING                   ; 1f
	const ST_GRAB_WALKING                  ; 20
	const ST_GRAB_AIRBORNE                 ; 21
	const ST_THROW_CHARGING                ; 22
	const ST_THROW_FULLY_CHARGED           ; 23
	const ST_THROWING                      ; 24
	const ST_THROWING_AIRBORNE             ; 25
	const ST_GRAB_SMASH_ATTACKING          ; 26
	const ST_SLIDING                       ; 27
	const ST_ROLLING                       ; 28
	const ST_ROLLING_AIRBORNE              ; 29
	const ST_UNKNOWN_2A                    ; 2a
	const ST_GROUND_SHAKE_STUNNED          ; 2b
	const ST_ENTERING_DOOR                 ; 2c
	const ST_UNKNOWN_2D                    ; 2d
	const ST_UNKNOWN_2E                    ; 2e
	const ST_UNKNOWN_2F                    ; 2f
	const ST_UNKNOWN_30                    ; 30
	const ST_UNKNOWN_31                    ; 31
	const ST_UNKNOWN_32                    ; 32
	const ST_UNKNOWN_33                    ; 33
	const ST_UNKNOWN_34                    ; 34
	const ST_UNKNOWN_35                    ; 35
	const ST_UNKNOWN_36                    ; 36
	const ST_UNKNOWN_37                    ; 37
	const ST_UNKNOWN_38                    ; 38
	const ST_UNKNOWN_39                    ; 39
	const ST_LADDER_CLIMBING               ; 3a
	const ST_LADDER_IDLING                 ; 3b
	const ST_LADDER_SHAKE_STUNNED          ; 3c
	const ST_GETTING_OFF_LADDER            ; 3d
	const ST_LADDER_SLIDING                ; 3e
	const ST_UNKNOWN_3F                    ; 3f
	const ST_UNKNOWN_40                    ; 40
	const ST_UNKNOWN_41                    ; 41
	const ST_UNKNOWN_42                    ; 42
	const ST_UNKNOWN_43                    ; 43
	const ST_UNKNOWN_44                    ; 44
	const ST_UNKNOWN_45                    ; 45
	const ST_UNKNOWN_46                    ; 46
	const ST_UNKNOWN_47                    ; 47
	const ST_UNKNOWN_48                    ; 48
	const ST_UNKNOWN_49                    ; 49
	const ST_UNKNOWN_4A                    ; 4a
	const ST_SLEEPING                      ; 4b
	const ST_LADDER_SCRATCHING             ; 4c
	const ST_UNKNOWN_4D                    ; 4d
	const ST_UNKNOWN_4E                    ; 4e
	const ST_UNKNOWN_4F                    ; 4f
	const ST_UNKNOWN_50                    ; 50
	const ST_UNKNOWN_51                    ; 51
	const ST_UNKNOWN_52                    ; 52
	const ST_UNKNOWN_53                    ; 53
	const ST_UNKNOWN_54                    ; 54
	const ST_UNKNOWN_55                    ; 55
	const ST_UNKNOWN_56                    ; 56
	const ST_UNKNOWN_57                    ; 57
	const ST_UNKNOWN_58                    ; 58
	const ST_UNKNOWN_59                    ; 59
	const ST_UNKNOWN_5A                    ; 5a
	const ST_UNKNOWN_5B                    ; 5b
	const ST_UNKNOWN_5C                    ; 5c
	const ST_UNKNOWN_5D                    ; 5d
	const ST_UNKNOWN_5E                    ; 5e
	const ST_UNKNOWN_5F                    ; 5f
	const ST_ON_FIRE                       ; 60
	const ST_ON_FIRE_AIRBORNE              ; 61
	const ST_HOT                           ; 62
	const ST_HOT_AIRBORNE                  ; 63
	const ST_BURNT                         ; 64
	const ST_UNKNOWN_65                    ; 65
	const ST_UNKNOWN_66                    ; 66
	const ST_UNKNOWN_67                    ; 67
	const ST_UNKNOWN_68                    ; 68
	const ST_UNKNOWN_69                    ; 69
	const ST_UNKNOWN_6A                    ; 6a
	const ST_UNKNOWN_6B                    ; 6b
	const ST_UNKNOWN_6C                    ; 6c
	const ST_UNKNOWN_6D                    ; 6d
	const ST_UNKNOWN_6E                    ; 6e
	const ST_UNKNOWN_6F                    ; 6f
	const ST_GETTING_WRAPPED_IN_STRING     ; 70
	const ST_BALL_O_STRING                 ; 71
	const ST_BALL_O_STRING_AIRBORNE        ; 72
	const ST_BALL_O_STRING_KNOCK_BACK      ; 73
	const ST_GETTING_UNWRAPPED_IN_STRING   ; 74
	const ST_BALL_O_STRING_DIZZY           ; 75
	const ST_FAT_BUMPING                   ; 76
	const ST_FAT_EATING                    ; 77
	const ST_FAT_IDLING                    ; 78
	const ST_FAT_WALKING                   ; 79
	const ST_FAT_TURNING                   ; 7a
	const ST_FAT_AIRBORNE                  ; 7b
	const ST_FAT_LANDING                   ; 7c
	const ST_FAT_SINKING                    ; 7d
	const ST_FAT_RECOVERING                ; 7e
	const ST_UNKNOWN_7F                    ; 7f
	const ST_ELECTRIC                      ; 80
	const ST_ELECTRIC_DIZZY                ; 81
	const ST_UNKNOWN_82                    ; 82
	const ST_UNKNOWN_83                    ; 83
	const ST_UNKNOWN_84                    ; 84
	const ST_UNKNOWN_85                    ; 85
	const ST_UNKNOWN_86                    ; 86
	const ST_ZOMBIE_IDLING                 ; 87
	const ST_ZOMBIE_WALKING                ; 88
	const ST_ZOMBIE_TURNING                ; 89
	const ST_ZOMBIE_AIRBORNE               ; 8a
	const ST_ZOMBIE_LANDING                ; 8b
	const ST_ZOMBIE_SLIPPING_THROUGH_FLOOR ; 8c
	const ST_ZOMBIE_RECOVERING             ; 8d
	const ST_ZOMBIE_KNOCK_BACK             ; 8e
	const ST_ZOMBIE_WRITHING               ; 8f
	const ST_UNKNOWN_90                    ; 90
	const ST_UNKNOWN_91                    ; 91
	const ST_UNKNOWN_92                    ; 92
	const ST_UNKNOWN_93                    ; 93
	const ST_UNKNOWN_94                    ; 94
	const ST_UNKNOWN_95                    ; 95
	const ST_UNKNOWN_96                    ; 96
	const ST_UNKNOWN_97                    ; 97
	const ST_UNKNOWN_98                    ; 98
	const ST_UNKNOWN_99                    ; 99
	const ST_UNKNOWN_9A                    ; 9a
	const ST_UNKNOWN_9B                    ; 9b
	const ST_UNKNOWN_9C                    ; 9c
	const ST_UNKNOWN_9D                    ; 9d
	const ST_UNKNOWN_9E                    ; 9e
	const ST_UNKNOWN_9F                    ; 9f
	const ST_UNKNOWN_A0                    ; a0
	const ST_UNKNOWN_A1                    ; a1
	const ST_UNKNOWN_A2                    ; a2
	const ST_UNKNOWN_A3                    ; a3
	const ST_UNKNOWN_A4                    ; a4
	const ST_UNKNOWN_A5                    ; a5
	const ST_UNKNOWN_A6                    ; a6
	const ST_UNKNOWN_A7                    ; a7
	const ST_UNKNOWN_A8                    ; a8
	const ST_UNKNOWN_A9                    ; a9
	const ST_UNKNOWN_AA                    ; aa
	const ST_UNKNOWN_AB                    ; ab
	const ST_UNKNOWN_AC                    ; ac
	const ST_UNKNOWN_AD                    ; ad
	const ST_UNKNOWN_AE                    ; ae
	const ST_UNKNOWN_AF                    ; af
	const ST_UNKNOWN_B0                    ; b0
	const ST_UNKNOWN_B1                    ; b1
	const ST_UNKNOWN_B2                    ; b2
	const ST_UNKNOWN_B3                    ; b3
	const ST_UNKNOWN_B4                    ; b4
	const ST_UNKNOWN_B5                    ; b5
	const ST_UNKNOWN_B6                    ; b6
	const ST_UNKNOWN_B7                    ; b7
	const ST_UNKNOWN_B8                    ; b8
	const ST_UNKNOWN_B9                    ; b9
	const ST_UNKNOWN_BA                    ; ba
	const ST_UNKNOWN_BB                    ; bb
	const ST_UNKNOWN_BC                    ; bc
	const ST_UNKNOWN_BD                    ; bd
	const ST_UNKNOWN_BE                    ; be
	const ST_UNKNOWN_BF                    ; bf
	const ST_UNKNOWN_C0                    ; c0
	const ST_UNKNOWN_C1                    ; c1
	const ST_UNKNOWN_C2                    ; c2
	const ST_UNKNOWN_C3                    ; c3
	const ST_UNKNOWN_C4                    ; c4
	const ST_UNKNOWN_C5                    ; c5
	const ST_UNKNOWN_C6                    ; c6
	const ST_UNKNOWN_C7                    ; c7
	const ST_UNKNOWN_C8                    ; c8
	const ST_UNKNOWN_C9                    ; c9
	const ST_UNKNOWN_CA                    ; ca
	const ST_UNKNOWN_CB                    ; cb
	const ST_UNKNOWN_CC                    ; cc
	const ST_UNKNOWN_CD                    ; cd
	const ST_UNKNOWN_CE                    ; ce
	const ST_UNKNOWN_CF                    ; cf
	const ST_UNKNOWN_D0                    ; d0
	const ST_UNKNOWN_D1                    ; d1
	const ST_UNKNOWN_D2                    ; d2
	const ST_UNKNOWN_D3                    ; d3
	const ST_UNKNOWN_D4                    ; d4
	const ST_UNKNOWN_D5                    ; d5
	const ST_UNKNOWN_D6                    ; d6
	const ST_UNKNOWN_D7                    ; d7
	const ST_UNKNOWN_D8                    ; d8
	const ST_UNKNOWN_D9                    ; d9
	const ST_UNKNOWN_DA                    ; da
	const ST_UNKNOWN_DB                    ; db
	const ST_UNKNOWN_DC                    ; dc
	const ST_UNKNOWN_DD                    ; dd
	const ST_UNKNOWN_DE                    ; de
	const ST_UNKNOWN_DF                    ; df
	const ST_UNKNOWN_E0                    ; e0
	const ST_UNKNOWN_E1                    ; e1
	const ST_UNKNOWN_E2                    ; e2
	const ST_UNKNOWN_E3                    ; e3
	const ST_UNKNOWN_E4                    ; e4
	const ST_UNKNOWN_E5                    ; e5
	const ST_UNKNOWN_E6                    ; e6
	const ST_UNKNOWN_E7                    ; e7
	const ST_UNKNOWN_E8                    ; e8
	const ST_UNKNOWN_E9                    ; e9
	const ST_UNKNOWN_EA                    ; ea
	const ST_UNKNOWN_EB                    ; eb
	const ST_UNKNOWN_EC                    ; ec
	const ST_UNKNOWN_ED                    ; ed
	const ST_UNKNOWN_EE                    ; ee
	const ST_UNKNOWN_EF                    ; ef
	const ST_UNKNOWN_F0                    ; f0
	const ST_UNKNOWN_F1                    ; f1
	const ST_UNKNOWN_F2                    ; f2
	const ST_UNKNOWN_F3                    ; f3
	const ST_UNKNOWN_F4                    ; f4
	const ST_UNKNOWN_F5                    ; f5
	const ST_UNKNOWN_F6                    ; f6
	const ST_UNKNOWN_F7                    ; f7
	const ST_UNKNOWN_F8                    ; f8
	const ST_UNKNOWN_F9                    ; f9
	const ST_UNKNOWN_FA                    ; fa
	const ST_UNKNOWN_FB                    ; fb
	const ST_UNKNOWN_FC                    ; fc
	const ST_UNKNOWN_FD                    ; fd
	const ST_UNKNOWN_FE                    ; fe
	const ST_UNKNOWN_FF                    ; ff
