	const_def
	const ST_IDLING                        ; 00
	const ST_WALKING                       ; 01
	const ST_TURNING                       ; 02
	const ST_UNUSED_03                     ; 03
	const ST_AIRBORNE                      ; 04
	const ST_LANDING                       ; 05
	const ST_CROUCH_SLIDING                ; 06
	const ST_ATTACKING                     ; 07
	const ST_ATTACKING_AIRBORNE            ; 08
	const ST_BUMPING                       ; 09
	const ST_DIVING                        ; 0a
	const ST_SUBMERGED                     ; 0b
	const ST_WATER_SURFACE_IDLING          ; 0c
	const ST_WATER_SURFACE_MOVING          ; 0d
	const ST_UNDERWATER_THRUSTING          ; 0e
	const ST_SWIM_KNOCK_BACK               ; 0f
	const ST_WATER_STUNG                   ; 10
	const ST_TRYING_SUBMERGE               ; 11
	const ST_CROUCHING                     ; 12
	const ST_CROUCH_WALKING                ; 13
	const ST_CROUCH_AIRBORNE               ; 14
	const ST_STUNG                         ; 15
	const ST_STUNG_RECOVERY                ; 16
	const ST_PIPE_GOING_DOWN               ; 17
	const ST_PIPE_GOING_UP                 ; 18
	const ST_ENEMY_BUMPING                 ; 19
	const ST_SMASH_ATTACKING               ; 1a
	const ST_UNUSED_1B                     ; 1b
	const ST_UNUSED_1C                     ; 1c
	const ST_UNUSED_1D                     ; 1d
	const ST_PICKING_UP                    ; 1e
	const ST_GRAB_IDLING                   ; 1f
	const ST_GRAB_WALKING                  ; 20
	const ST_GRAB_AIRBORNE                 ; 21
	const ST_THROW_CHARGING                ; 22
	const ST_THROW_FULLY_CHARGED           ; 23
	const ST_THROWING                      ; 24
	const ST_THROWING_AIRBORNE             ; 25
	const ST_GRAB_SMASH_ATTACKING          ; 26
	const ST_SLIDING                       ; 27
	const ST_ROLLING                       ; 28
	const ST_ROLLING_AIRBORNE              ; 29
	const ST_PICKED_UP                     ; 2a
	const ST_GROUND_SHAKE_STUNNED          ; 2b
	const ST_ENTERING_DOOR                 ; 2c
	const ST_UNUSED_2D                     ; 2d
	const ST_UNUSED_2E                     ; 2e
	const ST_UNUSED_2F                     ; 2f
	const ST_SLIPPING                      ; 30
	const ST_CROUCH_SLIPPING               ; 31
	const ST_DRAGGED_DOWN                  ; 32
	const ST_TELEPORTING                   ; 33
	const ST_UNKNOWN_34                    ; 34
	const ST_SAND_FALLING                  ; 35
	const ST_SAND_JUMPING                  ; 36
	const ST_SAND_IDLING                   ; 37
	const ST_SAND_WALKING                  ; 38
	const ST_SAND_TURNING                  ; 39
	const ST_LADDER_CLIMBING               ; 3a
	const ST_LADDER_IDLING                 ; 3b
	const ST_LADDER_SHAKE_SLIDING          ; 3c
	const ST_GETTING_OFF_LADDER            ; 3d
	const ST_LADDER_SLIDING                ; 3e
	const ST_GRAB_SLIPPING                 ; 3f
	const ST_UNKNOWN_40                    ; 40
	const ST_UNKNOWN_41                    ; 41
	const ST_UNKNOWN_42                    ; 42
	const ST_UNKNOWN_43                    ; 43
	const ST_UNKNOWN_44                    ; 44
	const ST_UNKNOWN_45                    ; 45
	const ST_UNKNOWN_46                    ; 46
	const ST_UNKNOWN_47                    ; 47
	const ST_UNKNOWN_48                    ; 48
	const ST_UNKNOWN_49                    ; 49
	const ST_UNKNOWN_4A                    ; 4a
	const ST_SLEEPING                      ; 4b
	const ST_LADDER_SCRATCHING             ; 4c
	const ST_FENCE_SHAKE_SLIDING           ; 4d
	const ST_FENCE_MOVING_VERTICAL         ; 4e
	const ST_FENCE_IDLING                  ; 4f
	const ST_FENCE_MOVING_HORIZONTAL       ; 50
	const ST_FENCE_SLIDING                 ; 51
	const ST_UNUSED_52                     ; 52
	const ST_UNUSED_53                     ; 53
	const ST_UNUSED_54                     ; 54
	const ST_UNUSED_55                     ; 55
	const ST_UNUSED_56                     ; 56
	const ST_UNUSED_57                     ; 57
	const ST_UNUSED_58                     ; 58
	const ST_UNUSED_59                     ; 59
	const ST_UNUSED_5A                     ; 5a
	const ST_UNUSED_5B                     ; 5b
	const ST_UNUSED_5C                     ; 5c
	const ST_UNUSED_5D                     ; 5d
	const ST_UNUSED_5E                     ; 5e
	const ST_UNUSED_5F                     ; 5f
	const ST_ON_FIRE                       ; 60
	const ST_ON_FIRE_AIRBORNE              ; 61
	const ST_HOT                           ; 62
	const ST_HOT_AIRBORNE                  ; 63
	const ST_BURNT                         ; 64
	const ST_GETTING_FLAT_AIRBORNE         ; 65
	const ST_GETTING_FLAT                  ; 66
	const ST_FLAT_IDLING                   ; 67
	const ST_FLAT_WALKING                  ; 68
	const ST_FLAT_JUMPING                  ; 69
	const ST_FLAT_FALLING                  ; 6a
	const ST_FLAT_STRETCHING               ; 6b
	const ST_FLAT_SINKING                  ; 6c
	const ST_FLAT_STRETCHING_UNDERWATER    ; 6d
	const ST_FLAT_SQUISHED                 ; 6e
	const ST_FLAT_SQUISHED_LIFTING         ; 6f
	const ST_GETTING_WRAPPED_IN_STRING     ; 70
	const ST_BALL_O_STRING                 ; 71
	const ST_BALL_O_STRING_AIRBORNE        ; 72
	const ST_BALL_O_STRING_KNOCK_BACK      ; 73
	const ST_GETTING_UNWRAPPED_IN_STRING   ; 74
	const ST_BALL_O_STRING_DIZZY           ; 75
	const ST_FAT_BUMPING                   ; 76
	const ST_FAT_EATING                    ; 77
	const ST_FAT_IDLING                    ; 78
	const ST_FAT_WALKING                   ; 79
	const ST_FAT_TURNING                   ; 7a
	const ST_FAT_AIRBORNE                  ; 7b
	const ST_FAT_LANDING                   ; 7c
	const ST_FAT_SINKING                   ; 7d
	const ST_FAT_RECOVERING                ; 7e
	const ST_ELECTRIC_START                ; 7f
	const ST_ELECTRIC                      ; 80
	const ST_ELECTRIC_DIZZY                ; 81
	const ST_TURNING_INVISIBLE             ; 82
	const ST_PUFFY_INFLATING               ; 83
	const ST_PUFFY_RISING                  ; 84
	const ST_PUFFY_TURNING                 ; 85
	const ST_PUFFY_DEFLATING               ; 86
	const ST_ZOMBIE_IDLING                 ; 87
	const ST_ZOMBIE_WALKING                ; 88
	const ST_ZOMBIE_TURNING                ; 89
	const ST_ZOMBIE_AIRBORNE               ; 8a
	const ST_ZOMBIE_LANDING                ; 8b
	const ST_ZOMBIE_SLIPPING_THROUGH_FLOOR ; 8c
	const ST_ZOMBIE_RECOVERING             ; 8d
	const ST_ZOMBIE_KNOCK_BACK             ; 8e
	const ST_ZOMBIE_WRITHING               ; 8f
	const ST_BOUNCY_START                  ; 90
	const ST_BOUNCY_FLOOR                  ; 91
	const ST_BOUNCY_AIRBORNE               ; 92
	const ST_BOUNCY_CEILING                ; 93
	const ST_BOUNCY_UPSIDE_DOWN            ; 94
	const ST_BOUNCY_UPSIDE_DOWN_LANDING    ; 95
	const ST_BOUNCY_LAST_BOUNCE            ; 96
	const ST_CRAZY_SPINNING                ; 97
	const ST_CRAZY_DIZZY                   ; 98
	const ST_CRAZY                         ; 99
	const ST_CRAZY_TURNING                 ; 9a
	const ST_CRAZY_AIRBORNE                ; 9b
	const ST_VAMPIRE_IDLING                ; 9c
	const ST_VAMPIRE_WALKING               ; 9d
	const ST_VAMPIRE_TURNING               ; 9e
	const ST_VAMPIRE_AIRBORNE              ; 9f
	const ST_BAT_TRANSFORMING              ; a0
	const ST_BAT_IDLING                    ; a1
	const ST_VAMPIRE_TRANSFORMING          ; a2
	const ST_BAT_FLYING                    ; a3
	const ST_BAT_FALLING                   ; a4
	const ST_IN_BUBBLE                     ; a5
	const ST_UNUSED_A6                     ; a6
	const ST_UNUSED_A7                     ; a7
	const ST_UNUSED_A8                     ; a8
	const ST_UNUSED_A9                     ; a9
	const ST_UNUSED_AA                     ; aa
	const ST_UNUSED_AB                     ; ab
	const ST_UNUSED_AC                     ; ac
	const ST_UNUSED_AD                     ; ad
	const ST_UNUSED_AE                     ; ae
	const ST_UNUSED_AF                     ; af
	const ST_ICE_SKATIN_START              ; b0
	const ST_ICE_SKATIN                    ; b1
	const ST_ICE_SKATIN_AIRBORNE           ; b2
	const ST_ICE_SKATIN_CRASH              ; b3
	const ST_UNUSED_B4                     ; b4
	const ST_UNUSED_B5                     ; b5
	const ST_UNUSED_B6                     ; b6
	const ST_UNUSED_B7                     ; b7
	const ST_UNKNOWN_B8                    ; b8
	const ST_UNKNOWN_B9                    ; b9
	const ST_UNKNOWN_BA                    ; ba
	const ST_UNKNOWN_BB                    ; bb
	const ST_UNKNOWN_BC                    ; bc
	const ST_UNUSED_BD                     ; bd
	const ST_UNUSED_BE                     ; be
	const ST_UNUSED_BF                     ; bf
	const ST_HANGING_RAIL                  ; c0
	const ST_UNUSED_C1                     ; c1
	const ST_UNUSED_C2                     ; c2
	const ST_UNUSED_C3                     ; c3
	const ST_UNKNOWN_C4                    ; c4
	const ST_UNKNOWN_C5                    ; c5
	const ST_UNKNOWN_C6                    ; c6
	const ST_UNKNOWN_C7                    ; c7
	const ST_UNKNOWN_C8                    ; c8
	const ST_UNKNOWN_C9                    ; c9
	const ST_UNKNOWN_CA                    ; ca
	const ST_UNKNOWN_CB                    ; cb
	const ST_UNKNOWN_CC                    ; cc
	const ST_UNKNOWN_CD                    ; cd
	const ST_UNUSED_CE                     ; ce
	const ST_UNUSED_CF                     ; cf
	const ST_SPLIT_HIT                     ; d0
	const ST_SPLIT_KNOCKED_BACK            ; d1
	const ST_SPLITTING                     ; d2
	const ST_UNKNOWN_D3                    ; d3
	const ST_UNKNOWN_D4                    ; d4
	const ST_UNKNOWN_D5                    ; d5
	const ST_UNKNOWN_D6                    ; d6
	const ST_UNKNOWN_D7                    ; d7
	const ST_UNKNOWN_D8                    ; d8
	const ST_UNUSED_D9                     ; d9
	const ST_UNUSED_DA                     ; da
	const ST_UNUSED_DB                     ; db
	const ST_BLIND_IDLING                  ; dc
	const ST_BLIND_WALKING                 ; dd
	const ST_BLIND_TURNING                 ; de
	const ST_BLIND_AIRBORNE                ; df
	const ST_UNKNOWN_E0                    ; e0
	const ST_UNKNOWN_E1                    ; e1
	const ST_UNKNOWN_E2                    ; e2
	const ST_UNUSED_E3                     ; e3
	const ST_MAGIC_RISING                  ; e4
	const ST_MAGIC_STOPPING                ; e5
	const ST_UNKNOWN_E6                    ; e6
	const ST_UNUSED_E7                     ; e7
	const ST_UNKNOWN_E8                    ; e8
	const ST_BALL_BOUNCING                 ; e9
	const ST_BALL_AIRBORNE                 ; ea
	const ST_BALL_SHOT                     ; eb
	const ST_BALL_THROWN                   ; ec
	const ST_BALL_SENT_UPWARDS             ; ed
	const ST_BALL_TURNING                  ; ee
	const ST_UNUSED_EF                     ; ef
	const ST_UNUSED_F0                     ; f0
	const ST_UNUSED_F1                     ; f1
	const ST_UNUSED_F2                     ; f2
