	const_def
	const TREASURE_NONE                ; $00
	const YELLOW_MUSIC_BOX             ; $01
	const BLUE_MUSIC_BOX               ; $02
	const GREEN_MUSIC_BOX              ; $03
	const RED_MUSIC_BOX                ; $04
	const GOLD_MUSIC_BOX               ; $05
	const PRINCE_FROGS_GLOVES_T        ; $06
	const SWIMMING_FLIPPERS_T          ; $07
	const HIGH_JUMP_BOOTS_T            ; $08
	const SUPER_GRAB_GLOVES_T          ; $09
	const GARLIC_T                     ; $0a
	const GRAB_GLOVE_T                 ; $0b
	const LEAD_OVERALLS_T              ; $0c
	const SUPER_JUMP_SLAM_OVERALLS_T   ; $0d
	const HEAD_SMASH_HELMET_T          ; $0e
	const LANTERN                      ; $0f
	const MAGICAL_FLAME                ; $10
	const TORCH                        ; $11
	const GEAR_1                       ; $12
	const GEAR_2                       ; $13
	const WARP_COMPACT                 ; $14
	const JAR                          ; $15
	const TREASURE_MAP                 ; $16
	const BLUE_BOOK                    ; $17
	const MAGIC_WAND                   ; $18
	const SKY_KEY                      ; $19
	const YELLOW_BOOK                  ; $1a
	const AXE                          ; $1b
	const TRIDENT                      ; $1c
	const SKULL_RING_BLUE              ; $1d
	const SKULL_RING_RED               ; $1e
	const BLUE_TABLET                  ; $1f
	const GREEN_TABLET                 ; $20
	const ORNAMENTAL_FAN               ; $21
	const TOP_HALF_OF_SCROLL           ; $22
	const BOTTOM_HALF_OF_SCROLL        ; $23
	const TUSK_BLUE                    ; $24
	const TUSK_RED                     ; $25
	const GREEN_FLOWER                 ; $26
	const BLUE_CHEMICAL                ; $27
	const RED_CHEMICAL                 ; $28
	const AIR_PUMP                     ; $29
	const SAPLING_OF_GROWTH            ; $2a
	const NIGHT_VISION_SCOPE           ; $2b
	const ELECTRIC_FAN_PROPELLER       ; $2c
	const RUST_SPRAY                   ; $2d
	const STATUE                       ; $2e
	const EXPLOSIVE_PLUNGER_BOX        ; $2f
	const SCISSORS                     ; $30
	const CASTLE_BRICK                 ; $31
	const WARP_REMOVAL_APPARATUS       ; $32
	const KEY_CARD_RED                 ; $33
	const KEY_CARD_BLUE                ; $34
	const JACKHAMMER                   ; $35
	const PICK_AXE                     ; $36
	const ROCKET                       ; $37
	const POCKET_PET                   ; $38
	const MYSTERY_HANDLE               ; $39
	const DEMONS_BLOOD                 ; $3a
	const GOLD_MAGIC                   ; $3b
	const FIGHTER_MANNEQUIN            ; $3c
	const TRUCK_WHEEL                  ; $3d
	const FLUTE                        ; $3e
	const FOOT_OF_STONE                ; $3f
	const GOLDEN_RIGHT_EYE             ; $40
	const GOLDEN_LEFT_EYE              ; $41
	const RIGHT_GLASS_EYE              ; $42
	const LEFT_GLASS_EYE               ; $43
	const SCEPTER                      ; $44
	const SUN_MEDALLION_TOP            ; $45
	const SUN_MEDALLION_BOTTOM         ; $46
	const EYE_OF_THE_STORM             ; $47
	const POUCH                        ; $48
	const MAGIC_SEEDS                  ; $49
	const FULL_MOON_GONG               ; $4a
	const TELEPHONE                    ; $4b
	const CROWN                        ; $4c
	const DAY_OR_NIGHT_SPELL           ; $4d
	const RED_GEM                      ; $4e
	const GREEN_GEM                    ; $4f
	const BLUE_GEM                     ; $50
	const CLUBS_CREST                  ; $51
	const SPADES_CREST                 ; $52
	const HEART_CREST                  ; $53
	const DIAMONDS_CREST               ; $54
	const EARTHEN_FIGURE               ; $55
	const SABER                        ; $56
	const GOBLET                       ; $57
	const TEAPOT                       ; $58
	const MAGNIFYING_GLASS             ; $59
	const UFO                          ; $5a
	const MINICAR                      ; $5b
	const LOCOMOTIVE                   ; $5c
	const FIRE_DRENCHER                ; $5d
	const CRAYON_RED_T                 ; $5e
	const CRAYON_BROWN_T               ; $5f
	const CRAYON_YELLOW_T              ; $60
	const CRAYON_GREEN_T               ; $61
	const CRAYON_CYAN_T                ; $62
	const CRAYON_BLUE_T                ; $63
	const CRAYON_PINK_T                ; $64
DEF NUM_TREASURES EQU const_value
	const TREASURE_DUMMY               ; $65
	const_def $80
	const INVALID_TREASURE             ; $80
	const_def $ed
DEF TREASURES_END EQU const_value

; pals
	const_def $4
	const OBPAL_TREASURE_YELLOW ; 4
	const OBPAL_TREASURE_RED    ; 5
	const OBPAL_TREASURE_GREEN  ; 6
	const OBPAL_TREASURE_BLUE   ; 7

DEF NUM_COLLECTION_COLS  EQU 5
DEF NUM_COLLECTION_ROWS  EQU 4
DEF NUM_COLLECTION_CELLS EQU NUM_COLLECTION_COLS * NUM_COLLECTION_ROWS
DEF NUM_COLLECTION_PAGES EQU NUM_TREASURES / NUM_COLLECTION_CELLS
DEF NUM_TREASURE_TILES   EQU 4
