; audio commands

MACRO audiocmd_unk
	db \1
	db \2
ENDM

MACRO audio_wait_12
	db $8c
ENDM

MACRO audio_wait_18
	db $92
ENDM

MACRO audio_wait_96
	db $b0
ENDM

MACRO audiocmd_jump
	db $b2
	dw \1 ; address
ENDM

MACRO audiocmd_call
	db $b3
	dw \1 ; address
ENDM

MACRO audiocmd_ret
	db $b4
ENDM

MACRO audiocmd_loop
	db $b5
	db \1 ; number of times + 1
	dw \2 ; address
ENDM

MACRO tempo
	db $bc
	db \1
ENDM

MACRO pitch_offset
	db $bd
	db \1
ENDM

MACRO wave
	db $be
	db \1
ENDM

MACRO audiocmd_bf
	db $bf
	db \1
ENDM

MACRO vibrato_speed
	db $c3
	db \1
ENDM

MACRO vibrato_delay
	db $c4
	db \1
ENDM

MACRO vibrato_amplitude
	db $c5
	db \1
ENDM

MACRO set_vibrato_disabled
	db $c6
	db \1
ENDM

MACRO audiocmd_ca
	db $ca
	db \1
ENDM

MACRO set_timbre
	db $d1
	db \1
ENDM

MACRO fade_in
	db $d2
	db \1 ; speed
ENDM

MACRO fade_out
	db $d5
	db \1 ; speed
ENDM

MACRO audiocmd_d6
	db $d6
	db \1
ENDM

MACRO audiocmd_d7
	db $d7
	db \1
ENDM

MACRO set_duration
	db $da
	db \1
ENDM

MACRO set_sweep
	db $db
	db \1
ENDM

DEF NOTE_DURATION_0  EQU $cf
DEF NOTE_DURATION_1  EQU $d0
DEF NOTE_DURATION_2  EQU $d1
DEF NOTE_DURATION_3  EQU $d2
DEF NOTE_DURATION_4  EQU $d3
DEF NOTE_DURATION_5  EQU $d4
DEF NOTE_DURATION_6  EQU $d5
DEF NOTE_DURATION_7  EQU $d6
DEF NOTE_DURATION_8  EQU $d7
DEF NOTE_DURATION_9  EQU $d8
DEF NOTE_DURATION_10 EQU $d9
DEF NOTE_DURATION_11 EQU $da
DEF NOTE_DURATION_12 EQU $db
DEF NOTE_DURATION_13 EQU $dc
DEF NOTE_DURATION_14 EQU $dd
DEF NOTE_DURATION_15 EQU $de
DEF NOTE_DURATION_16 EQU $df
DEF NOTE_DURATION_17 EQU $d0
DEF NOTE_DURATION_18 EQU $d1
DEF NOTE_DURATION_19 EQU $d2
DEF NOTE_DURATION_20 EQU $d3
DEF NOTE_DURATION_21 EQU $d4
DEF NOTE_DURATION_22 EQU $d5
DEF NOTE_DURATION_23 EQU $d6
DEF NOTE_DURATION_24 EQU $d7
DEF NOTE_DURATION_28 EQU $d8
DEF NOTE_DURATION_30 EQU $d9
DEF NOTE_DURATION_32 EQU $da
DEF NOTE_DURATION_36 EQU $db
DEF NOTE_DURATION_40 EQU $dc
DEF NOTE_DURATION_42 EQU $dd
DEF NOTE_DURATION_44 EQU $de
DEF NOTE_DURATION_48 EQU $df
DEF NOTE_DURATION_52 EQU $d0
DEF NOTE_DURATION_54 EQU $d1
DEF NOTE_DURATION_56 EQU $d2
DEF NOTE_DURATION_60 EQU $d3
DEF NOTE_DURATION_64 EQU $d4
DEF NOTE_DURATION_66 EQU $d5
DEF NOTE_DURATION_68 EQU $d6
DEF NOTE_DURATION_72 EQU $d7
DEF NOTE_DURATION_76 EQU $d8
DEF NOTE_DURATION_78 EQU $d9
DEF NOTE_DURATION_80 EQU $da
DEF NOTE_DURATION_84 EQU $db
DEF NOTE_DURATION_88 EQU $dc
DEF NOTE_DURATION_90 EQU $dd
DEF NOTE_DURATION_92 EQU $de
DEF NOTE_DURATION_96 EQU $df

DEF C_0 EQU $24
DEF C#0 EQU $25
DEF D_0 EQU $26
DEF D#0 EQU $27
DEF E_0 EQU $28
DEF F_0 EQU $29
DEF F#0 EQU $2a
DEF G_0 EQU $2b
DEF G#0 EQU $2c
DEF A_0 EQU $2d
DEF A#0 EQU $2e
DEF B_0 EQU $2f
DEF C_1 EQU $30
DEF C#1 EQU $31
DEF D_1 EQU $32
DEF D#1 EQU $33
DEF E_1 EQU $34
DEF F_1 EQU $35
DEF F#1 EQU $36
DEF G_1 EQU $37
DEF G#1 EQU $38
DEF A_1 EQU $39
DEF A#1 EQU $3a
DEF B_1 EQU $3b
DEF C_2 EQU $3c
DEF C#2 EQU $3d
DEF D_2 EQU $3e
DEF D#2 EQU $3f
DEF E_2 EQU $40
DEF F_2 EQU $41
DEF F#2 EQU $42
DEF G_2 EQU $43
DEF G#2 EQU $44
DEF A_2 EQU $45
DEF A#2 EQU $46
DEF B_2 EQU $47
DEF C_3 EQU $48
DEF C#3 EQU $49
DEF D_3 EQU $4a
DEF D#3 EQU $4b
DEF E_3 EQU $4c
DEF F_3 EQU $4d
DEF F#3 EQU $4e
DEF G_3 EQU $4f
DEF G#3 EQU $50
DEF A_3 EQU $51
DEF A#3 EQU $52
DEF B_3 EQU $53
DEF C_4 EQU $54
DEF C#4 EQU $55
DEF D_4 EQU $56
DEF D#4 EQU $57
DEF E_4 EQU $58
DEF F_4 EQU $59
DEF F#4 EQU $5a
DEF G_4 EQU $5b
DEF G#4 EQU $5c
DEF A_4 EQU $5d
DEF A#4 EQU $5e
DEF B_4 EQU $5f
DEF C_5 EQU $60
DEF C#5 EQU $61
DEF D_5 EQU $62
DEF D#5 EQU $63
DEF E_5 EQU $64
DEF F_5 EQU $65
DEF F#5 EQU $66
DEF G_5 EQU $67
DEF G#5 EQU $68
DEF A_5 EQU $69
DEF A#5 EQU $6a
DEF B_5 EQU $6b
DEF C_6 EQU $6c
DEF C#6 EQU $6d
DEF D_6 EQU $6e
DEF D#6 EQU $6f
DEF E_6 EQU $70
DEF F_6 EQU $71
DEF F#6 EQU $72
DEF G_6 EQU $73
DEF G#6 EQU $74
DEF A_6 EQU $75
DEF A#6 EQU $76
DEF B_6 EQU $77
DEF C_7 EQU $78
DEF C#7 EQU $79
DEF D_7 EQU $7a
DEF D#7 EQU $7b
DEF E_7 EQU $7c
DEF F_7 EQU $7d
DEF F#7 EQU $7e
DEF G_7 EQU $7f

MACRO note
	assert \1 >= NOTE_DURATION_0 && \1 <= NOTE_DURATION_96
	db \1 ; duration
IF _NARG == 2
	db \2
ELIF _NARG == 3
	db \2, \3
ELIF _NARG == 4
	db \2, \3, \4
ENDC
ENDM
