MACRO level_music
REPT 4
	dw \1
ENDR
REPT 4
	dw \2
ENDR
ENDM

LevelMusic:: ; 3fe40 (f:7e40)
;               day                             night
	level_music MUSIC_OUT_OF_THE_WOODS_DAY,     MUSIC_OUT_OF_THE_WOODS_NIGHT     ; OUT_OF_THE_WOODS
	level_music MUSIC_THE_PEACEFUL_VILLAGE_DAY, MUSIC_THE_PEACEFUL_VILLAGE_NIGHT ; THE_PEACEFUL_VILLAGE
	level_music MUSIC_THE_VAST_PLAIN_DAY,       MUSIC_THE_VAST_PLAIN_NIGHT       ; THE_VAST_PLAIN
	level_music MUSIC_BANK_OF_THE_WILD_RIVER,   MUSIC_BANK_OF_THE_WILD_RIVER     ; BANK_OF_THE_WILD_RIVER
	level_music MUSIC_THE_TIDAL_COAST,          MUSIC_THE_TIDAL_COAST            ; THE_TIDAL_COAST
	level_music MUSIC_THE_TIDAL_COAST,          MUSIC_THE_TIDAL_COAST            ; SEA_TURTLE_ROCKS
	level_music MUSIC_DESERT_RUINS,             MUSIC_DESERT_RUINS               ; DESERT_RUINS
	level_music MUSIC_THE_VOLCANOS_BASE_DAY,    MUSIC_THE_VOLCANOS_BASE_NIGHT    ; THE_VOLCANOS_BASE
	level_music MUSIC_THE_POOL_OF_RAIN_DAY,     MUSIC_THE_POOL_OF_RAIN_NIGHT     ; THE_POOL_OF_RAIN
	level_music MUSIC_THE_PEACEFUL_VILLAGE_DAY, MUSIC_THE_PEACEFUL_VILLAGE_NIGHT ; A_TOWN_IN_CHAOS
	level_music MUSIC_THE_TIDAL_COAST,          MUSIC_THE_TIDAL_COAST            ; BENEATH_THE_WAVES
	level_music MUSIC_THE_WEST_CRATER,          MUSIC_THE_WEST_CRATER            ; THE_WEST_CRATER
	level_music MUSIC_THE_VAST_PLAIN_DAY,       MUSIC_THE_VAST_PLAIN_NIGHT       ; THE_GRASSLANDS
	level_music MUSIC_BANK_OF_THE_WILD_RIVER,   MUSIC_BANK_OF_THE_WILD_RIVER     ; THE_BIG_BRIDGE
	level_music MUSIC_DESERT_RUINS,             MUSIC_DESERT_RUINS               ; TOWER_OF_REVIVAL
	level_music MUSIC_BANK_OF_THE_WILD_RIVER,   MUSIC_BANK_OF_THE_WILD_RIVER     ; THE_STEEP_CANYON
	level_music MUSIC_CAVE_OF_FLAMES,           MUSIC_CAVE_OF_FLAMES             ; CAVE_OF_FLAMES
	level_music MUSIC_ABOVE_THE_CLOUDS_DAY,     MUSIC_ABOVE_THE_CLOUDS_NIGHT     ; ABOVE_THE_CLOUDS
	level_music MUSIC_THE_POOL_OF_RAIN_DAY,     MUSIC_THE_POOL_OF_RAIN_NIGHT     ; THE_STAGNANT_SWAMP
	level_music MUSIC_THE_FRIGID_SEA,           MUSIC_THE_FRIGID_SEA             ; THE_FRIGID_SEA
	level_music MUSIC_THE_VOLCANOS_BASE_DAY,    MUSIC_THE_VOLCANOS_BASE_NIGHT    ; CASTLE_OF_ILLUSIONS
	level_music MUSIC_CAVE_OF_FLAMES,           MUSIC_CAVE_OF_FLAMES             ; THE_COLOSSAL_HOLE
	level_music MUSIC_THE_WARPED_VOID,          MUSIC_THE_WARPED_VOID            ; THE_WARPED_VOID
	level_music MUSIC_THE_WEST_CRATER,          MUSIC_THE_WEST_CRATER            ; THE_EAST_CRATER
	level_music MUSIC_FOREST_OF_FEAR,           MUSIC_FOREST_OF_FEAR             ; FOREST_OF_FEAR
; 0x3ffd0
