TransformationMusicIDs::
	dw NULL
	dw MUSIC_HOT_WARIO           ; TRANSFORMATION_HOT_WARIO_ID
	dw MUSIC_FLAT_WARIO          ; TRANSFORMATION_FLAT_WARIO_ID
	dw MUSIC_BALL_O_STRING_WARIO ; TRANSFORMATION_BALL_O_STRING_WARIO_ID
	dw MUSIC_FAT_WARIO           ; TRANSFORMATION_FAT_WARIO_ID
	dw NULL                      ; TRANSFORMATION_ELECTRIC_ID
	dw MUSIC_INVISIBLE_WARIO     ; TRANSFORMATION_INVISIBLE_WARIO_ID
	dw NULL                      ; TRANSFORMATION_PUFFY_WARIO_ID
	dw MUSIC_ZOMBIE_WARIO        ; TRANSFORMATION_ZOMBIE_WARIO_ID
	dw MUSIC_BOUNCY_WARIO        ; TRANSFORMATION_BOUNCY_WARIO_ID
	dw MUSIC_CRAZY_WARIO         ; TRANSFORMATION_CRAZY_WARIO_ID
	dw MUSIC_VAMPIRE_WARIO       ; TRANSFORMATION_VAMPIRE_WARIO_ID
	dw NULL                      ; TRANSFORMATION_BUBBLE_ID
	dw NULL                      ; TRANSFORMATION_ICE_SKATIN_ID
	dw MUSIC_OWL_WARIO           ; TRANSFORMATION_OWL_WARIO_ID
	dw NULL                      ; TRANSFORMATION_RAIL_ID
	dw MUSIC_SNOWMAN_WARIO       ; TRANSFORMATION_SNOWMAN_WARIO_ID
	dw NULL                      ; TRANSFORMATION_SPLIT_ID
	dw NULL                      ; TRANSFORMATION_FAN_ID
	dw NULL                      ; TRANSFORMATION_BLIND_ID
	dw NULL                      ; TRANSFORMATION_LAUNCHED_ID
	dw NULL                      ; TRANSFORMATION_MAGIC_ID
	dw NULL                      ; TRANSFORMATION_BALL_ID
	dw NULL
	dw NULL
	dw NULL
	dw NULL
	dw NULL
	dw NULL
	dw NULL
	dw NULL
	dw NULL
