INCLUDE "macros/audio.asm"
INCLUDE "macros/audio_commands.asm"
INCLUDE "macros/constants.asm"
INCLUDE "macros/code.asm"
INCLUDE "macros/data.asm"
INCLUDE "macros/gfx.asm"
INCLUDE "macros/pos.asm"
INCLUDE "macros/wram.asm"
